stages:
  train:
    cmd: python src/ml_pipeline-for-deployment.py
    deps:
    - src/data/raw_useful_ftrs.csv
    - src/data/features_to_use_summary.csv
    outs:	
    - src/data/input_data_sample.csv
    - src/visualization/mdl_performance.png
    metrics:
    - src/metrics/best_model_cv_summary.json:
        cache: false